id: P009515
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:35:56.197914
source_metadata:
  id: bdr:W1KG25692
  title: བོད་ལྗོངས་སློབ་གྲྭ་ཆེན་མོའི་རིག་དེབ་ཀྱི་བོད་རིག་པའི་ཞིབ་འཇུག་དཔྱད་རྩོམ་གཅེས་བཏུས།
  author: ''
  volumes:
    5c2486497c2c43359820623aad2aa474:
      image_group_id: I1KG25694
      title: ''
      volume_number: 1
      total_pages: 715
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
